services:
  # A Docker web service
  - type: web
    name: fastapi-example
    runtime: python
    plan: free
    autoDeploy: false
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    env:
    - DATABASE_HOSTNAME: ${DATABASE_HOSTNAME}
    - DATABASE_PORT: ${DATABASE_PORT}
    - DATABASE_PASSWORD: ${DATABASE_PASSWORD}
    - DATABASE_NAME: ${DATABASE_NAME}
    - DATABASE_USERNAME: ${DATABASE_USERNAME}
    - SECRET_KEY: ${SECRET_KEY}
    - ALGORITHM: ${ALGORITHM}
    - ACCESS_TOKEN_EXPIRE_MINUTES: ${ACCESS_TOKEN_EXPIRE_MINUTES}